---
repos:
    - repo: https://github.com/sqlfluff/sqlfluff
      rev: 0.9.0
      hooks:
          - id: sqlfluff-fix
            exclude: ^migrations/00000000000000_diesel_initial_setup
          - id: sqlfluff-lint
            exclude: ^migrations/00000000000000_diesel_initial_setup
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
    - repo: https://github.com/psf/black
      rev: 19.3b0
      hooks:
          - id: black
    - repo: https://github.com/pappasam/toml-sort
      rev: v0.19.0
      hooks:
          - id: toml-sort
            args: [--in-place, --all]
