---
repos:
    - repo: https://github.com/sqlfluff/sqlfluff
      rev: 0.9.0
      hooks:
          - id: sqlfluff-fix
          - id: sqlfluff-lint
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
    - repo: https://github.com/psf/black
      rev: 19.3b0
      hooks:
          - id: black
    - repo: https://github.com/DevinR528/cargo-sort
      rev: v1.0.7
      hooks:
          - id: cargo-sort
    - repo: local
      hooks:
          - id: sqlx-check
            name: Check sqlx-data
            entry: cargo sqlx prepare --check -- --lib
            language: system
            types: [rust]
            pass_filenames: false
