[package]
name = "cavalcade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amq-protocol = "6"
serde = "1"
tokio = {version="1", features=["net", "io-util", "rt", "macros", "rt-multi-thread"] }
anyhow = "1"
bytes = "1"
regex = "1"
lazy_static = "1"
diesel = { version = "1.4", features = ["postgres"] }
dotenv = "0.15.0"

[dev-dependencies]
celery = "0.4.0-rcn.11"
simplelog = "*" 