[package]
edition = "2021"
name = "cavalcade"
version = "0.1.0"

[dependencies]
amq-protocol = "6"
anyhow = "1"
bytes = "1"
diesel = { version = "1.4", features = ["postgres", "r2d2", "serde_json"] }
dotenv = "0.15.0"
lazy_static = "1"
r2d2 = "0.8"
regex = "1"
serde = "1"
serde_json = "*"
tokio = { version = "1", features = ["net", "io-util", "rt", "macros", "rt-multi-thread"] }

[dev-dependencies]
celery = "0.4.0-rcn.11"
simplelog = "*"
