[package]
name = "cavalcade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amq-protocol = "*"
serde = "*"
tokio = "*"
anyhow = "*"

[dev-dependencies]
celery = "0.4.0-rcn.11" 