---
version: '3'
services:
    db:
        image: postgres:13
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: cavalcade

    cavalcade:
        build: .
        volumes:
            - .:/work
        command: bash -c "cargo build && wait-for-db --mode postgres --connection-string postgres://postgres:password@db/cavalcade && diesel migration run
            && cargo run"
        environment:
            DATABASE_URL: postgres://postgres:password@db/cavalcade

    test-celery:
        build:
            context: tests
            dockerfile: Dockerfile.celery_test
        environment:
            AMQP_HOST: cavalcade
        command: wait-for-it --host=cavalcade --port=5672 --timeout=0 --strict -- python test_tasks.py worker --loglevel=DEBUG
        volumes:
            - ./tests:/work
